apiRules:
- include:
    # Including the OmiyaGames.Saves namespace
    uidRegex: ^OmiyaGames\.Saves$
    type: Namespace
- include:
    # Including the OmiyaGames.Saves.Editor namespace
    uidRegex: ^OmiyaGames\.Saves\.Editor$
    type: Namespace
- include:
    uidRegex: ^Global
    type: Namespace
- exclude:
    # Taro Omiya: note that I'm ignoring namespaces containing unit tests on purpooses
    uidRegex: .*
    type: Namespace
